//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.23 at 10:40:13 AM EDT 
//


package com.york.api.data;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.york.api.data package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PlaceSearchResponse_QNAME = new QName("", "placeSearchResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.york.api.data
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PlaceSearchResponse }
     * 
     */
    public PlaceSearchResponse createPlaceSearchResponse() {
        return new PlaceSearchResponse();
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link Viewport }
     * 
     */
    public Viewport createViewport() {
        return new Viewport();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link Photo }
     * 
     */
    public Photo createPhoto() {
        return new Photo();
    }

    /**
     * Create an instance of {@link Geometry }
     * 
     */
    public Geometry createGeometry() {
        return new Geometry();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PlaceSearchResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "placeSearchResponse")
    public JAXBElement<PlaceSearchResponse> createPlaceSearchResponse(PlaceSearchResponse value) {
        return new JAXBElement<PlaceSearchResponse>(_PlaceSearchResponse_QNAME, PlaceSearchResponse.class, null, value);
    }

}
